### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by makeclean** [ukaea/overlap_checker#15]
In the end i figured out how this is meant to work

1) ./step_to_brep <step_file> <brep_file>
2) ./overlap_check -j N <brep_file> > overlaps.csv
3) ./imprint_solids <brep_file> <output brep file> < overlaps.csv

Does that seem correct?

**Comment by smason** [comment]
that looks right; see the "Running" section of the readme:

  https://github.com/ukaea/overlap_checker#running

maybe I could move things around to put that nearer the top?

**Comment by johnnonweiler** [comment]
@makeclean - If there's an issue here, then please clarify what you think is needed and reopen this issue.
