### ISSUE TITLE
switch to build tools more commonly used by UKAEA

### ISSUE THREAD

**Issue by smason** [ukaea/overlap_checker#6]
* CMake instead of meson
 * Spack instead of conan
 * maybe drop spdlog and CLI11 as dependencies

**Comment by smason** [comment]
waiting on Andrew to give feedback!

**Comment by makeclean** [comment]
Sorry, been some sickness at home, I'll take a look :)

**Comment by smason** [comment]
> Sorry, been some sickness at home, I'll take a look :)

No probs, hope you're feeling better

While doing this have reminded myself why I like the `fmt` and `doctests` libraries over `iostreams` and `catch2`.  STL streams are very painful to get formatted output that reads nicely.  While `catch2` takes an age to compile, which is very annoying when making small fixes.

@makeclean, I'd encourage you to make these libraries generally available for use in these sorts of tools!

**Comment by makeclean** [comment]
How long does the build take on your machine? On mine build time is 16 seconds

**Comment by smason** [comment]
> How long does the build take on your machine? On mine build time is 16 seconds

sounds about right, but adds up over time and adds friction reducing motivation to recompile/test for small changes.
